name: Java CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v4.2.2
      with: 
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

    - name: Build with Maven
      run: mvn clean install

    - name: Download ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        mv chromedriver /usr/local/bin/

    - name: Run tests
      run: mvn test
