name: Java CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs at midnight UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '22'
        cache: 'maven'
        cache-dependency-path: 'pom.xml' # optional


    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1.7.2

    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v2.2.2

    - name: Build with Maven
      run: mvn clean install

    - name: Test with Maven
      run: mvn test